-- 1. Create the Videos table
-- This table stores video metadata. 'video_id' is the unique Primary Key.
CREATE TABLE IF NOT EXISTS tesla_videos (
    video_id TEXT PRIMARY KEY,
    brand TEXT,
    title TEXT,
    channel_title TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    view_count BIGINT,
    like_count BIGINT,
    comment_count_reported BIGINT,
    label TEXT
);

-- 2. Create the Comments table
-- This table links to tesla_videos. 
-- It also allows for threaded comments via 'parent_comment_id'.
CREATE TABLE IF NOT EXISTS tesla_comments (
    comment_id TEXT PRIMARY KEY,
    video_id TEXT REFERENCES tesla_videos(video_id) ON DELETE CASCADE,
    parent_comment_id TEXT REFERENCES tesla_comments(comment_id),
    comment_type TEXT,
    author TEXT,
    text TEXT,
    like_count BIGINT,
    published_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    brand TEXT,
    label TEXT
);

-- 3. Create the News table
-- This table uses an auto-incrementing ID.
-- If your CSV doesn't have an 'id' column, Postgres will generate one automatically.
CREATE TABLE IF NOT EXISTS tesla_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand TEXT,
    article_uri TEXT,
    title TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    source TEXT,
    url TEXT,
    lang TEXT,
    body_text TEXT
);

-- Optional: Create indexes for better query performance on foreign keys
CREATE INDEX IF NOT EXISTS idx_comments_video_id ON tesla_comments(video_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON tesla_comments(parent_comment_id);
